#Quinton Dean
#This program converts ASCII  for greek letters and prints them

lowerAlpha = chr(945)
lowerBeta = chr(946)
lowerLamda = chr(955)
lowerGamma = chr(947)
lowerDelta = chr(948)
lowerTheta = chr(952)
lowerPi = chr(960)
lowerSigma = chr(963)
lowerOmega = chr(969)
theta = chr(920)
lamda = chr(923)
pi = chr(928)
sigma = chr(931)
omega = chr(937)
beta = chr(914)
gamma = chr(915)
delta = chr(916)
alpha = chr(913)

print(format(lowerAlpha, ">17"))
#print(end = '\n')
print(format(lowerBeta, ">9")
+format(lowerGamma, ">8")
+format(lowerDelta, ">8"))
#print(end = '\n')
print(lowerTheta
+format(lowerLamda, ">8")
+format(lowerPi, ">8")
      +format(lowerSigma, ">8")
      +format(lowerOmega, ">8")
      )
print(theta
      +format(lamda, ">8")
      +format(pi, ">8")
      +format(sigma, ">8")
      +format(omega, ">8")
      )
print(format(beta, ">9")
      +format(gamma, ">8")
      +format(delta, ">8")
      )
print(format(alpha, ">17"))
